on:
  push:
    branches:
        - '**'
    tags-ignore:
        - '**'
  pull_request_target:
    types:
      - "labeled"
jobs:
  move-code:
    if: ${{ (github.event.label.name == 'basic-review-passed' && github.event.action == 'labeled') || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ahoylabs/copybara-action@v0.0.1
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: ahoylabs/faraday
          destination_repo: ahoylabs/faraday-guides
          copybara_options: "--force"
          push_include: "apps/docs/** .github/workflows/move-repo__docs.yml"
          push_move: "apps/docs||"
          pr_move: |
            ||apps/docs
            apps/docs/.github||.github
